services:
  app:
    restart: always
    build: .
    ports:
      - "8080:5080"
    environment:
      - DB_HOST=mariadb
      - DB_USER=monitoringAdm
      - DB_PASSWORD=Dimok22123
      - DB_NAME=Monitoring
    depends_on:
      - mariadb
    command: sh -c "sleep 5 && npm run dev"

  mariadb:
    image: mariadb:lts-ubi9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Dimok22123
      MYSQL_USER: monitoringAdm                   # Имя пользователя
      MYSQL_PASSWORD: Dimok22123
      MYSQL_DATABASE: Monitoring
    ports:
      - "3306:3306"
    volumes:
      - /opt/databases/db4cams:/var/lib/mysql

volumes:
  mariadb_data: 